# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lesson4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lesson4
  pod 'RealmSwift', '=10.1.4'
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'

end
